# Generated by Django 3.2 on 2021-06-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='updateAd',
            new_name='updateAt',
        ),
    ]
